CREATE DATABASE IF NOT EXISTS test
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE test

CREATE TABLE IF NOT EXISTS users(
	email VARCHAR(64) PRIMARY KEY COMMENT "email",
	password VARCHAR(32),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
